title: ztech
author: bambang indra wahyudi
email: bambangindraw@gmail.com
description: > baru belajar
theme: minima

# social links
twitter_username: bambangindraWHY
github_username:  bambangindraw

show_excerpts: true # set to false to remove excerpts on the homepage
