title: my sites
Theme:minima
author: bambang indra wahyudi
email: bambangindraw@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Milik pribadi

# social links
twitter_username: bambangindraWHY
github_username:  bambangindraw.github.io

show_excerpts: true # set to false to remove excerpts on the homepage
